---

- name: Test for swap partition
  shell: 'swapon -s | grep -E "^/"'
  changed_when: false
  failed_when: false
  register: swap_exists

- name: Create swapfile
  shell: "dd if=/dev/zero of=/var/swap.img bs=1024k count=1000"
  when: swap_exists.rc

- name: change swap file permissions
  file:
    path: /var/swap.img
    owner: root
    group: root
    mode: 0600
  when: swap_exists.rc

- name: Prepare swapfile
  shell: mkswap /var/swap.img warn=no
  when: swap_exists.rc

- name: Enable swap
  shell: swapon /var/swap.img warn=no
  when: swap_exists.rc

- name: write swap entry to fstab
  when: swap_exists.rc
  mount:
    name: none
    src: /var/swap.img
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present

- name: configure swappiness
  when: swap_exists.rc
  lineinfile:
    path: /etc/sysctl.conf
    line: vm.swappiness=50
